# Generated by Django 6.0 on 2025-12-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=2)),
                ('cpf', models.IntegerField(max_length=11)),
                ('contract_time', models.IntegerField()),
                ('salary', models.FloatField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_sector', to='employee.sector')),
            ],
        ),
    ]
