# Generated by Django 6.0 on 2026-01-06 19:24

import django.core.validators
import django.db.models.deletion
import localflavor.br.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchical_Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hierarchical_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('age', models.IntegerField()),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(14), localflavor.br.validators.BRCPFValidator()])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('contract_time', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('access_allowed', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('hierarchical_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_hierarchical', to='employee.hierarchical_level')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_sector', to='employee.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
