# Generated by Django 6.0 on 2025-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
