# Generated by Django 6.0 on 2025-12-14 01:15

import django.core.validators
import localflavor.br.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contract_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), localflavor.br.validators.BRCPFValidator()]),
        ),
    ]
