# Generated by Django 6.0 on 2025-12-14 01:22

import django.core.validators
import localflavor.br.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_contract_time_alter_employee_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(14), localflavor.br.validators.BRCPFValidator()]),
        ),
    ]
