# Generated by Django 6.0 on 2025-12-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchical_Level',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hierarchical_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Activate', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='hierarchical_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_hierarchical', to='employee.hierarchical_level'),
        ),
    ]
